# Generated by Django 3.0.13 on 2021-09-19 06:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date and Time')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modification Date and Time')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True, verbose_name='Object UUID')),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'genre',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date and Time')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modification Date and Time')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True, verbose_name='Object UUID')),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'instrument',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date and Time')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modification Date and Time')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True, verbose_name='Object UUID')),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'keyword',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Master_Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date and Time')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modification Date and Time')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True, verbose_name='Object UUID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'master_owner',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Mode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date and Time')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modification Date and Time')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True, verbose_name='Object UUID')),
                ('name', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'mode',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date and Time')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modification Date and Time')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True, verbose_name='Object UUID')),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'mood',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Production_Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date and Time')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modification Date and Time')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True, verbose_name='Object UUID')),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'production_style',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date and Time')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modification Date and Time')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True, verbose_name='Object UUID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'publisher',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Time_Signature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date and Time')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modification Date and Time')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True, verbose_name='Object UUID')),
                ('name', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'time_signature',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date and Time')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modification Date and Time')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True, verbose_name='Object UUID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('bpm', models.IntegerField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('sounds_like', models.CharField(blank=True, max_length=255, null=True)),
                ('tv_usage', models.BooleanField(blank=True, null=True)),
                ('stock_sales', models.BooleanField(blank=True, null=True)),
                ('data_complete', models.BooleanField(blank=True, null=True)),
                ('overall_quality', models.IntegerField(blank=True, null=True)),
                ('music_key', models.CharField(max_length=8)),
                ('is_exclusive', models.BooleanField(default=False)),
                ('exclusive_contact', models.CharField(blank=True, max_length=128, null=True)),
                ('exclusive_phone', models.CharField(blank=True, max_length=128, null=True)),
                ('exclusive_email', models.CharField(blank=True, max_length=128, null=True)),
                ('publisher_split', models.CharField(blank=True, max_length=512, null=True)),
                ('writer_split', models.CharField(blank=True, max_length=512, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('genre', models.ManyToManyField(blank=True, null=True, to='music_collection_search.Genre')),
                ('instrument', models.ManyToManyField(blank=True, null=True, to='music_collection_search.Instrument')),
                ('keyword', models.ManyToManyField(blank=True, null=True, to='music_collection_search.Keyword')),
                ('mode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='music_collection_search.Mode')),
                ('mood', models.ManyToManyField(blank=True, null=True, to='music_collection_search.Mood')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='music_collection_search.Master_Owner')),
                ('production_style', models.ManyToManyField(blank=True, null=True, to='music_collection_search.Production_Style')),
                ('publisher', models.ManyToManyField(blank=True, null=True, to='music_collection_search.Publisher')),
                ('time_signature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='music_collection_search.Time_Signature')),
            ],
            options={
                'db_table': 'song',
                'managed': True,
            },
        ),
    ]
