# Generated by Django 3.0.13 on 2021-09-28 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_collection_search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mode',
            name='name',
            field=models.CharField(max_length=16),
        ),
    ]
