version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./music_lib_search_tool:/code
    environment:
      - DJANGO_SETTINGS_MODULE=music_lib_search_tool.settings.dev
    ports:
      - "8000:8000"
    depends_on:
      - db

